# ?? ?? ??
server:
  port: 8253
  servlet:
    encoding:
      charset: UTF-8

# mariaDb, jpa ??
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${RDS_DATABASE_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS-PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    encoding: UTF-8


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml
  type-aliases-package: spring.hi_hello_spring.**

token:
  secret: ${TOKEN_SECRET}
  expiration_time: ${TOKEN_EXPIRATION_TIME}

refresh-token:
  expiration_time: ${REFRESHTOKEN_EXPIRATION_TIME}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

logging.level:
  org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
