# ?? ?? ??
server:
  port: 8253
  servlet:
    encoding:
      charset: UTF-8

# mariaDb, jpa ??
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${RDS_DATABASE_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${REDIS_PASSWORD}
    mongodb:
      uri: mongodb://${MONGO_USER_NANE}:${MONGO_PASSWORD}@localhost:27017/hihello?authSource=admin
    elasticsearch:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  kafka:
    consumer:
      group-id: chat-group
      auto-offset-reset: latest
    bootstrap-servers: ${KAFKA_HOST_NAME}:9092
    producer:
      bootstrap-servers: localhost
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    alert-topic-name: an-alert
    accept-topic-name: an-accept
  server:
    port: 8253
  elasticsearch:
    uris: ${ELASTIC_URIS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    wiki:
      index:
        name: wiki
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/**/*.xml
  type-aliases-package: spring.hi_hello_spring.**

token:
  secret: ${TOKEN_SECRET}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

logging.level:
  org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none