# ?? ?? ??
server:
  port: 8100
  servlet:
    encoding:
      charset: UTF-8

# mysql, jpa ??
spring:
  profiles:
    include: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
